<?php

namespace MJH\WsseBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use MJH\WsseBundle\Entity\Nonce;
use \DateTime;

/**
 * NonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NonceRepository extends EntityRepository
{
  public function verifyAndPersistNonce($nonce, $username, $duration)
  {
    $entity = $this->getEntityManager()
            ->createQuery('SELECT n FROM
              MjhWsseBundle:Nonce n
              WHERE n.nonce = :nonce AND
              n.auth_token = :username')
            ->setParameter('nonce', $nonce)
            ->setParameter('username', $username)
            ->getOneOrNullResult();
    
    if (!$entity)
    { 
      $newNonce = new Nonce();
      $newNonce->setNonce( $nonce );
      $newNonce->setCreatedAt( new DateTime() );
      $newNonce->setAuthToken( $username );
      $em = $this->getEntityManager();
      
      if ($nonce)
      {
        $em->persist($newNonce);
      $em->flush();
      }
      
      
      return true;
    }
    
    
    return false;
  }
}